services:
  postgres:
    image: postgres

  mongo:
    image: mongo
    
  mongo-express:
    image: mongo-express
    
  rabbitmq:
    image: rabbitmq:3-management-alpine  
  
  adminer:
    image: adminer
     
volumes:
  postgres_data:
  mongodata:  