services:
  postgres:
    container_name: bidbay_db
    restart: always
    ports:
     - 7721:5432
    environment:
     - POSTGRES_PASSWORD=bidbay
    volumes:
     - postgres_data:/var/lib/postgresql/data

  mongo:
    container_name: bidbay_mongo
    restart: always
    ports:
     - 7722:27017
    environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: bidbay_pw
    volumes:
     - mongodata:/etc/mongo
 
     
  mongo-express:
    container_name: mongo-express
    restart: always
    ports:
     - 7723:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:bidbay_pw@mongo:27017
      ME_CONFIG_MONDOGB_ADMINPASSWORD: bidbay_pw
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_BASICAUTH: false
    depends_on:
     - mongo

  rabbitmq:
    container_name: bidbay_transport  
    ports:
     - 5672:5672
     - 15672:15672 
    
  adminer:
     restart: always
     container_name: bidbay_adminer
     ports:
      - 8080:8080   